### ISSUE TITLE
JPEG writing with coefficients and quantization matrix

### ISSUE THREAD

**Issue by ehgusehgus** [dwgoon/jpegio#13]
Is there a function that save jpeg file with the DCT coefficients and quantization matrix directly?(not with the pixel values)

Thank you for reading

**Comment by dwgoon** [comment]
You can use `write` method as follows

```Python
import jpegio as jio

jpeg = jio.read("image.jpg")
# Modifying jpeg.coef_arrays...
# Modifying jpeg.quant_tables...
jio.write(jpeg, "image_modified.jpg")
```

**Comment by ehgusehgus** [comment]
jpegio.write() function seems to cause error.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ehgus\Anaconda3\lib\site-packages\jpegio-0.2.1-py3.6-win-amd64.egg\jpegio\io.py", line 20, in write
    obj.write(fpath)
  File "jpegio\decompressedjpeg.pyx", line 195, in jpegio.decompressedjpeg.DecompressedJpeg.write
  File "jpegio\decompressedjpeg.pyx", line 196, in jpegio.decompressedjpeg.DecompressedJpeg.write
  File "jpegio\decompressedjpeg.pyx", line 200, in jpegio.decompressedjpeg.DecompressedJpeg._write_markers
TypeError: object of type 'NoneType' has no len()

**Comment by dwgoon** [comment]
Refer to the code snippet again, and correct your code as follows, please.
```Python
jio.write(jpeg, "image_modified.jpg")
```

**Comment by ehgusehgus** [comment]
Yes. I've tried like this.

import jpegio
c = jpegio.read('input.jpg')
jpegio.write(c,'image_modified.jpg')

But it produces error like below.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ehgus\Anaconda3\lib\site-packages\jpegio-0.2.1-py3.6-win-amd64.egg\jpegio\io.py", line 20, in write
    obj.write(fpath)
  File "jpegio\decompressedjpeg.pyx", line 195, in jpegio.decompressedjpeg.DecompressedJpeg.write
  File "jpegio\decompressedjpeg.pyx", line 196, in jpegio.decompressedjpeg.DecompressedJpeg.write
  File "jpegio\decompressedjpeg.pyx", line 200, in jpegio.decompressedjpeg.DecompressedJpeg._write_markers
TypeError: object of type 'NoneType' has no len()

**Comment by dwgoon** [comment]
Thanks for giving me the hint.
I've fixed jpeg.write following your comment.
Test the revised code, please.
