### ISSUE TITLE
Cannot read some jpeg files

### ISSUE THREAD

**Issue by CauchyComplete** [dwgoon/jpegio#14]
![000000095843](https://user-images.githubusercontent.com/24504012/89789582-beee0c00-db5b-11ea-8c7e-2eb6e5fa8be2.jpg)

This image is from COCO 2017 valid, but jpegio cannot read this file. There are several files in COCO that jpegio cannot read.
`` jpegio.read("000000095843.jpg") ``
gives
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 31:  invalid start byte
Although, PIL can read this file.

**Comment by dwgoon** [comment]
Could you tell me about your working environment such as OS, python version, etc?

**Comment by CauchyComplete** [comment]
@dwgoon It's Windows 10, python 3.6. Now I've tried in python 3.7 and got the exact same error.
``Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Frank\Anaconda3\envs\temp\lib\site-packages\jpegio-0.2.1-py3.7-win-amd64.egg\jpegio\io.py", line 8, in read
    obj.read(fpath)
  File "jpegio\decompressedjpeg.pyx", line 34, in jpegio.decompressedjpeg.DecompressedJpeg.read
  File "jpegio\decompressedjpeg.pyx", line 47, in jpegio.decompressedjpeg.DecompressedJpeg.read
  File "jpegio\decompressedjpeg.pyx", line 104, in jpegio.decompressedjpeg.DecompressedJpeg._read_markers
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 31: invalid start byte``

**Comment by dwgoon** [comment]
I have changed the type of `DecompressedJpeg.markers`. From now on, users should decode the `bytes` to `str` using an appropriate encoding scheme.

**Comment by CauchyComplete** [comment]
@dwgoon Thanks for fixing. It works.

**Comment by dwgoon** [comment]
That sounds great :)
