### ISSUE TITLE
Compiling executable on Windows 7 with Pyinstaller 3.6

### ISSUE THREAD

**Issue by asrabon** [dwgoon/jpegio#6]
Whenever I compile my script utilizing jpegio into an executable using Windows 10 it works without any issue. However, on Windows 7 when I move the executable to another machine it will give me an error message.

Traceback (most recent call last):
File "get_dct.py", line 1, in
File "c:\users\win7investi\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
File "site-packages\jpegio-0.2.1-py3.6-win32.egg\jpegio_init_.py", line 7, in
ImportError: DLL load failed: The specified module could not be found.
[4076] Failed to execute script get_dct

**Comment by dwgoon** [comment]
It seems that the problem is related to PyInstaller problems or Windows versions.
Could you please give me more information on your Windows versions and architectures?
